# -*- coding: utf-8 -*-
"""converte_dados_raman.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0NMwMFmpXIqklPl-kHSgKHZAaLMOUQH
"""

import re
import os
import glob
from pathlib import Path
import pandas as pd
import numpy as np
from datetime import datetime
import csv

from google.colab import drive
drive.mount('/content/drive')

path =  '/content/drive/MyDrive/Colab Notebooks/Arcelor_sinter/'

field = ["time", "data"]

CSVreport = open(path + 'raman_data.csv', 'w', newline='')
wr = csv.writer(CSVreport, delimiter=',', quoting=csv.QUOTE_NONE, escapechar=' ')
wr.writerow(field)

txt_files = glob.glob(os.path.join(path + 'RAMAN_09-05-23_NOVO/', "*.txt"))

# loop over the list of csv files
for f in txt_files:
  regex = re.compile(r"(\d+_\d+_\d+)") # pattern to capture date
  matchArray = regex.findall(f)
  date = matchArray[0]
  date  = datetime.strptime(date, "%d_%m_%Y").strftime('%d-%m-%Y')
  print(date)

  data = pd.read_csv(f, delimiter=';')
  raw_data = data['Espectro']
  #smooth_data = data['Espectro_Smooth']
  s = [date, np.asarray(raw_data)]
  wr.writerow([s[0], ','.join(map(str, s[1]))])

CSVreport.close()

s = [date, np.asarray(raw_data)]

date_object = datetime.strptime(s[0], '%d-%m-%Y').date()
print(date_object)